[package]
name = "fatrs"
version = "0.1.0"
authors = ["archshift <gh@archshift.com>"]
build = "build.rs"

[dependencies]
lazy_static = "1.0"
rcstring = "0.2"
spin = { version = "0.4", default-features = false }

[build-dependencies]
cc = "1.0"
bindgen = "0.32"
